# Generated by Django 4.1.7 on 2023-07-07 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0067_remove_discount_event_delete_discount2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('date', models.CharField(blank=True, max_length=255)),
                ('time', models.CharField(blank=True, max_length=255)),
                ('ticket_type', models.CharField(blank=True, max_length=255)),
                ('price', models.CharField(blank=True, max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('order_number', models.CharField(blank=True, max_length=255)),
                ('custom_1', models.CharField(blank=True, max_length=255)),
                ('barcode', models.CharField(blank=True, max_length=255)),
                ('text_field_1', models.TextField(blank=True)),
                ('text_field_2', models.TextField(blank=True)),
                ('text_field_3', models.TextField(blank=True)),
                ('text_field_4', models.TextField(blank=True)),
                ('text_field_5', models.TextField(blank=True)),
                ('text_field_6', models.TextField(blank=True)),
                ('text_field_7', models.TextField(blank=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.event')),
            ],
        ),
    ]
