# Generated by Django 4.1.7 on 2023-07-14 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomTicketFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('value', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='ticket',
            name='custom_fields',
            field=models.ManyToManyField(blank=True, to='ticket.customticketfields'),
        ),
    ]
