# Generated by Django 4.1.7 on 2023-07-17 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_customticketfields_ticket_custom_fields'),
        ('ticket', '0003_remove_ticket_custom_fields_ticket_custom_1_and_more'),
    ]

    operations = [
    ]
