# Generated by Django 4.1.7 on 2023-08-16 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0007_alter_ticket_text_field_1_alter_ticket_text_field_4_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='text_field_5',
            field=models.TextField(blank=True, default='<b>THIS IS YOUR TICKET:</b> <font color="blue">This e-ticket is valid on your phone</font>, printed in black and white or colour and MUST have a clear and valid barcode. This e-ticket is only valid for the date and time it states above.<br /><br />\n                                                            <b>TICKETS ARE NON-TRANSFERABLE AND NON-REFUNDABLE.</b><br /> <font color="red"><u>Unauthorized duplication or sale of a ticket is prohibited.</u></font>The Wilder Institute/Calgary Zoo is not responsible for any inconvenience caused by unauthorized duplication and reserve the right to deny entry and/or suspend membership privileges.'),
        ),
    ]
