# Generated by Django 4.1.7 on 2023-04-13 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_datetime_event"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datetime",
            name="event",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to="core.event",
            ),
        ),
    ]
