# Generated by Django 4.1.7 on 2023-04-13 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_datetime_event"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="facility",
            name="event",
        ),
        migrations.AddField(
            model_name="event",
            name="event",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.facility",
            ),
        ),
    ]
