# Generated by Django 4.1.7 on 2023-04-13 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_remove_facility_event_event_event"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="event",
            new_name="facility",
        ),
    ]
