# Generated by Django 4.1.7 on 2023-04-14 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_event_facility"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="facility",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.facility",
            ),
        ),
    ]
