# Generated by Django 4.1.7 on 2023-04-14 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_alter_event_facility"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pricetype",
            name="price_layer",
        ),
        migrations.AddField(
            model_name="pricetype",
            name="event",
            field=models.ManyToManyField(to="core.event"),
        ),
        migrations.AddField(
            model_name="pricetypelayer",
            name="price_type",
            field=models.ManyToManyField(null=True, to="core.pricetype"),
        ),
    ]
