# Generated by Django 4.1.7 on 2023-04-14 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_remove_pricetype_price_layer_pricetype_event_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pricetype",
            name="event",
        ),
        migrations.AddField(
            model_name="event",
            name="price_type",
            field=models.ManyToManyField(to="core.pricetype"),
        ),
    ]
