# Generated by Django 4.1.7 on 2023-04-14 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_remove_pricetype_value"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pricetype",
            old_name="price_type_name",
            new_name="name",
        ),
    ]
