# Generated by Django 4.1.7 on 2023-04-14 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_rename_price_type_name_pricetype_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="PriceLayer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name="event",
            name="price_type",
            field=models.ManyToManyField(
                related_name="price_type", to="core.pricetype"
            ),
        ),
        migrations.DeleteModel(
            name="PriceTypeLayer",
        ),
        migrations.AddField(
            model_name="event",
            name="price_layer",
            field=models.ManyToManyField(to="core.pricelayer"),
        ),
    ]
