# Generated by Django 4.1.7 on 2023-04-14 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_pricelayerprice_price_layer_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pricelayerprice",
            name="event",
            field=models.OneToOneField(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="core.event"
            ),
            preserve_default=False,
        ),
    ]
