# Generated by Django 4.1.7 on 2023-04-14 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_alter_pricelayerprice_event"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="price_layer",
            field=models.ManyToManyField(null=True, to="core.pricelayer"),
        ),
        migrations.AlterField(
            model_name="event",
            name="price_type",
            field=models.ManyToManyField(null=True, to="core.pricetype"),
        ),
    ]
