# Generated by Django 4.1.7 on 2023-04-20 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_alter_event_price_layer_alter_event_price_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="status",
            field=models.CharField(
                choices=[
                    ("OS", "On Sale"),
                    ("P", "Pending"),
                    ("S", "Setup"),
                    ("AN", "Action Needed"),
                    ("C", "Concluded"),
                ],
                default="STATUS_PENDING",
                max_length=2,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="websales_link",
            field=models.CharField(default="test.com", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="event",
            name="website_link",
            field=models.CharField(default="test2.com", max_length=255),
            preserve_default=False,
        ),
    ]
