# Generated by Django 4.1.7 on 2023-04-20 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_event_status_event_websales_link_event_website_link"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="location",
            name="event",
        ),
        migrations.AddField(
            model_name="event",
            name="location",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.location",
            ),
        ),
    ]
