# Generated by Django 4.1.7 on 2023-04-20 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_remove_location_event_event_location"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="datetime",
            name="sell_time",
        ),
        migrations.RemoveField(
            model_name="datetime",
            name="stop_time",
        ),
        migrations.AlterField(
            model_name="datetime",
            name="sell_date",
            field=models.DateTimeField(),
        ),
    ]
