# Generated by Django 4.1.7 on 2023-04-20 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_remove_datetime_sell_time_remove_datetime_stop_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="datetime",
            name="on_sale_date",
            field=models.DateTimeField(default="2023-04-01 06:04"),
            preserve_default=False,
        ),
    ]
