# Generated by Django 4.1.7 on 2023-04-20 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_datetime_on_sale_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="datetime",
            name="event_end_time",
            field=models.TimeField(default="06:00"),
            preserve_default=False,
        ),
    ]
