# Generated by Django 4.1.7 on 2023-04-20 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_datetime_event_end_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pricelayerprice",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="price_layer_price",
                to="core.event",
            ),
        ),
    ]
