# Generated by Django 4.1.7 on 2023-04-20 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0027_remove_pricelayerprice_price_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pricelayerprice",
            name="price_layer",
        ),
        migrations.AddField(
            model_name="pricelayerprice",
            name="price_layer",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.pricelayer",
            ),
            preserve_default=False,
        ),
    ]
