# Generated by Django 4.1.7 on 2023-04-20 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0029_rename_price_pricelayerprice_layer_1_price_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pricelayerprice",
            old_name="layer_2_layer",
            new_name="price_layer",
        ),
        migrations.RenameField(
            model_name="pricelayerprice",
            old_name="layer_2_type",
            new_name="price_type",
        ),
        migrations.RemoveField(
            model_name="pricelayerprice",
            name="layer_1_layer",
        ),
        migrations.RemoveField(
            model_name="pricelayerprice",
            name="layer_1_price",
        ),
        migrations.RemoveField(
            model_name="pricelayerprice",
            name="layer_1_type",
        ),
        migrations.RemoveField(
            model_name="pricelayerprice",
            name="layer_2_price",
        ),
    ]
