# Generated by Django 4.1.7 on 2023-04-21 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0031_pricelayerprice_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="price_layer",
        ),
        migrations.RemoveField(
            model_name="event",
            name="price_type",
        ),
    ]
