# Generated by Django 4.1.7 on 2023-04-21 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0032_remove_event_price_layer_remove_event_price_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="GLAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gl_account", models.CharField(max_length=255)),
                ("description", models.CharField(max_length=255)),
                ("event", models.ManyToManyField(to="core.event")),
                (
                    "price_layer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.pricelayer",
                    ),
                ),
            ],
        ),
    ]
