# Generated by Django 4.1.7 on 2023-04-26 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0035_discount"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="datetime",
            name="on_sale_date",
        ),
    ]
