# Generated by Django 4.1.7 on 2023-04-26 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0036_remove_datetime_on_sale_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="timeslot",
            name="event",
        ),
        migrations.AddField(
            model_name="event",
            name="time_slot",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.timeslot",
            ),
        ),
    ]
