# Generated by Django 4.1.7 on 2023-04-26 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0037_remove_timeslot_event_event_time_slot"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="time_slot",
        ),
        migrations.AddField(
            model_name="event",
            name="time_slot",
            field=models.ManyToManyField(null=True, to="core.timeslot"),
        ),
    ]
