# Generated by Django 4.1.7 on 2023-04-26 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0038_remove_event_time_slot_event_time_slot"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="time_slot",
        ),
        migrations.AddField(
            model_name="timeslot",
            name="event",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.PROTECT, to="core.event"
            ),
            preserve_default=False,
        ),
    ]
