# Generated by Django 4.1.7 on 2023-04-26 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0039_remove_event_time_slot_timeslot_event"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timeslot",
            name="time_range",
            field=models.CharField(
                choices=[("0600", "6:00 - 6:30 AM"), ("0630", "6:30 - 7:00 AM")],
                default="6:00 - 6:30 AM",
                max_length=4,
            ),
        ),
    ]
