# Generated by Django 4.1.7 on 2023-04-26 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0040_alter_timeslot_time_range"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timeslot",
            name="time_range",
            field=models.CharField(
                choices=[("6:00 - 6:30 AM", "0600"), ("6:30 - 7:00 AM", "0630")],
                default="6:00 - 6:30 AM",
                max_length=14,
            ),
        ),
    ]
