# Generated by Django 4.1.7 on 2023-04-27 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0043_alter_prices_price_1_alter_prices_price_2_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Prices",
            new_name="Price",
        ),
    ]
