# Generated by Django 4.1.7 on 2023-04-30 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0044_rename_prices_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pricelayerprice",
            name="event",
        ),
        migrations.AddField(
            model_name="pricelayerprice",
            name="event",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="price_layer_price",
                to="core.event",
            ),
            preserve_default=False,
        ),
    ]
