# Generated by Django 4.1.7 on 2023-04-30 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0045_remove_pricelayerprice_event_pricelayerprice_event"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="entrance",
            field=models.CharField(
                choices=[
                    ("North Entrance", "N"),
                    ("South Entrance", "S"),
                    ("West Entrance", "W"),
                ],
                default="NORTH_ENTRANCE",
                max_length=14,
            ),
        ),
    ]
