# Generated by Django 4.1.7 on 2023-04-30 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0046_alter_event_entrance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="entrance",
            field=models.CharField(
                choices=[("N", "North"), ("S", "South"), ("W", "West")],
                default="NORTH_ENTRANCE",
                max_length=1,
            ),
        ),
    ]
