# Generated by Django 4.1.7 on 2023-04-30 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0048_alter_event_entrance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="csi_mandatory",
            field=models.CharField(
                choices=[("Yes", "Y"), ("No", "N")], default="NO_CHOICE", max_length=3
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="csi_needed",
            field=models.CharField(
                choices=[("Yes", "Y"), ("No", "N")], default="NO_CHOICE", max_length=3
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="early_closure",
            field=models.CharField(
                choices=[("Yes", "Y"), ("No", "N")], default="NO_CHOICE", max_length=3
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="gr_required",
            field=models.CharField(
                choices=[("Yes", "Y"), ("No", "N")], default="NO_CHOICE", max_length=3
            ),
        ),
    ]
