# Generated by Django 4.1.7 on 2023-05-10 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0049_alter_event_csi_mandatory_alter_event_csi_needed_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timeslot",
            name="time_range",
            field=models.CharField(
                choices=[
                    ("6:00 - 6:30 AM", "0600"),
                    ("6:30 - 7:00 AM", "0630"),
                    ("7:00 - 7:30 AM", "0700"),
                    ("7:30 - 8:00 AM", "0730"),
                ],
                default="6:00 - 6:30 AM",
                max_length=14,
            ),
        ),
    ]
