# Generated by Django 4.1.7 on 2023-05-11 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0051_alter_timeslot_time_range"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="discount",
            name="event",
        ),
        migrations.AddField(
            model_name="discount",
            name="event",
            field=models.OneToOneField(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="core.event"
            ),
            preserve_default=False,
        ),
    ]
