# Generated by Django 4.1.7 on 2023-05-11 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0054_alter_discount_event"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discount",
            name="price_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="price_type",
                to="core.pricetype",
            ),
        ),
    ]
