# Generated by Django 4.1.7 on 2023-05-11 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0055_alter_discount_price_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="discount",
            name="event",
        ),
        migrations.AlterField(
            model_name="discount",
            name="price_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.pricetype"
            ),
        ),
        migrations.AddField(
            model_name="discount",
            name="event",
            field=models.ManyToManyField(related_name="discount", to="core.event"),
        ),
    ]
