# Generated by Django 4.1.7 on 2023-05-12 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0056_remove_discount_event_alter_discount_price_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Discount2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("discount", models.CharField(max_length=255)),
                ("description", models.CharField(max_length=255)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discount2",
                        to="core.event",
                    ),
                ),
                (
                    "price_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.pricetype"
                    ),
                ),
            ],
        ),
    ]
