# Generated by Django 4.1.7 on 2023-05-12 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0059_rename_accounts_account"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="accountlayer",
            name="event",
        ),
        migrations.AddField(
            model_name="accountlayer",
            name="event",
            field=models.ManyToManyField(to="core.event"),
        ),
    ]
