# Generated by Django 4.1.7 on 2023-05-12 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0060_remove_accountlayer_event_accountlayer_event"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accountlayer",
            name="event",
            field=models.ManyToManyField(related_name="account", to="core.event"),
        ),
    ]
