# Generated by Django 4.1.7 on 2023-05-16 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0061_alter_accountlayer_event"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account",
            name="description",
        ),
    ]
