# Generated by Django 4.1.7 on 2023-05-16 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0062_remove_account_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="accountlayer",
            name="event",
        ),
        migrations.AddField(
            model_name="accountlayer",
            name="event",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="account",
                to="core.event",
            ),
            preserve_default=False,
        ),
    ]
