# Generated by Django 4.1.7 on 2023-05-16 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0064_alter_accountlayer_event"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accountlayer",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="account",
                to="core.event",
            ),
        ),
    ]
