# Generated by Django 4.1.7 on 2023-06-16 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0065_alter_accountlayer_event"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pricelayerprice",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
