# Generated by Django 4.1.7 on 2023-07-18 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_remove_accountlayer_event_accountlayer_event'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountlayer',
            old_name='account',
            new_name='gl_account',
        ),
    ]
