# Generated by Django 4.1.7 on 2023-07-20 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_alter_glaccount_gl_account'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GLAccount',
        ),
    ]
