# Generated by Django 4.1.7 on 2023-07-26 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0072_delete_glaccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='additional_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='websales_link',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='event',
            name='website_link',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
