# Generated by Django 4.1.7 on 2023-08-18 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0073_alter_event_additional_notes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountlayer',
            name='event',
        ),
        migrations.AddField(
            model_name='accountlayer',
            name='event',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='account', to='core.event'),
            preserve_default=False,
        ),
    ]
